export type MechEngine = {
  engineRating: number;
  tonnage: number;
  integralHeatSinks: number;
  maxIntegralHeatSinks: number;
};

export const mechEngines: MechEngine[] = [
  { engineRating: 20, tonnage: 0.5, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 25, tonnage: 0.5, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 30, tonnage: 1, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 35, tonnage: 1, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 40, tonnage: 1, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 45, tonnage: 1, integralHeatSinks: 0, maxIntegralHeatSinks: 1 },
  { engineRating: 50, tonnage: 1.5, integralHeatSinks: 0, maxIntegralHeatSinks: 2 },
  { engineRating: 55, tonnage: 1.5, integralHeatSinks: 0, maxIntegralHeatSinks: 2 },
  { engineRating: 60, tonnage: 1.5, integralHeatSinks: 0, maxIntegralHeatSinks: 2 },
  { engineRating: 65, tonnage: 2, integralHeatSinks: 0, maxIntegralHeatSinks: 2 },
  { engineRating: 70, tonnage: 2, integralHeatSinks: 0, maxIntegralHeatSinks: 2 },
  { engineRating: 75, tonnage: 2, integralHeatSinks: 0, maxIntegralHeatSinks: 3 },
  { engineRating: 80, tonnage: 2.5, integralHeatSinks: 0, maxIntegralHeatSinks: 3 },
  { engineRating: 85, tonnage: 2.5, integralHeatSinks: 0, maxIntegralHeatSinks: 3 },
  { engineRating: 90, tonnage: 3, integralHeatSinks: 0, maxIntegralHeatSinks: 3 },
  { engineRating: 95, tonnage: 3, integralHeatSinks: 0, maxIntegralHeatSinks: 3 },
  { engineRating: 100, tonnage: 3, integralHeatSinks: 0, maxIntegralHeatSinks: 4 },
  { engineRating: 105, tonnage: 3.5, integralHeatSinks: 0, maxIntegralHeatSinks: 4 },
  { engineRating: 110, tonnage: 3.5, integralHeatSinks: 0, maxIntegralHeatSinks: 4 },
  { engineRating: 115, tonnage: 4, integralHeatSinks: 0, maxIntegralHeatSinks: 4 },
  { engineRating: 120, tonnage: 4, integralHeatSinks: 0, maxIntegralHeatSinks: 4 },
  { engineRating: 125, tonnage: 4, integralHeatSinks: 0, maxIntegralHeatSinks: 5 },
  { engineRating: 130, tonnage: 4.5, integralHeatSinks: 0, maxIntegralHeatSinks: 5 },
  { engineRating: 135, tonnage: 4.5, integralHeatSinks: 0, maxIntegralHeatSinks: 5 },
  { engineRating: 140, tonnage: 5, integralHeatSinks: 0, maxIntegralHeatSinks: 5 },
  { engineRating: 145, tonnage: 5, integralHeatSinks: 0, maxIntegralHeatSinks: 5 },
  { engineRating: 150, tonnage: 5.5, integralHeatSinks: 0, maxIntegralHeatSinks: 6 },
  { engineRating: 155, tonnage: 5.5, integralHeatSinks: 0, maxIntegralHeatSinks: 6 },
  { engineRating: 160, tonnage: 6, integralHeatSinks: 0, maxIntegralHeatSinks: 6 },
  { engineRating: 165, tonnage: 6, integralHeatSinks: 0, maxIntegralHeatSinks: 6 },
  { engineRating: 170, tonnage: 6, integralHeatSinks: 0, maxIntegralHeatSinks: 6 },
  { engineRating: 175, tonnage: 7, integralHeatSinks: 0, maxIntegralHeatSinks: 7 },
  { engineRating: 180, tonnage: 7, integralHeatSinks: 0, maxIntegralHeatSinks: 7 },
  { engineRating: 185, tonnage: 7.5, integralHeatSinks: 0, maxIntegralHeatSinks: 7 },
  { engineRating: 190, tonnage: 7.5, integralHeatSinks: 0, maxIntegralHeatSinks: 7 },
  { engineRating: 195, tonnage: 8, integralHeatSinks: 0, maxIntegralHeatSinks: 7 },
  { engineRating: 200, tonnage: 8.5, integralHeatSinks: 0, maxIntegralHeatSinks: 8 },
  { engineRating: 205, tonnage: 8.5, integralHeatSinks: 0, maxIntegralHeatSinks: 8 },
  { engineRating: 210, tonnage: 9, integralHeatSinks: 0, maxIntegralHeatSinks: 8 },
  { engineRating: 215, tonnage: 9.5, integralHeatSinks: 0, maxIntegralHeatSinks: 8 },
  { engineRating: 220, tonnage: 10, integralHeatSinks: 0, maxIntegralHeatSinks: 8 },
  { engineRating: 225, tonnage: 10, integralHeatSinks: 0, maxIntegralHeatSinks: 9 },
  { engineRating: 230, tonnage: 10.5, integralHeatSinks: 0, maxIntegralHeatSinks: 9 },
  { engineRating: 235, tonnage: 11, integralHeatSinks: 0, maxIntegralHeatSinks: 9 },
  { engineRating: 240, tonnage: 11.5, integralHeatSinks: 0, maxIntegralHeatSinks: 9 },
  { engineRating: 245, tonnage: 12, integralHeatSinks: 0, maxIntegralHeatSinks: 9 },
  { engineRating: 250, tonnage: 12.5, integralHeatSinks: 0, maxIntegralHeatSinks: 10 },
  { engineRating: 255, tonnage: 13, integralHeatSinks: 0, maxIntegralHeatSinks: 10 },
  { engineRating: 260, tonnage: 13.5, integralHeatSinks: 0, maxIntegralHeatSinks: 10 },
  { engineRating: 265, tonnage: 14, integralHeatSinks: 0, maxIntegralHeatSinks: 10 },
  { engineRating: 270, tonnage: 14.5, integralHeatSinks: 0, maxIntegralHeatSinks: 10 },
  { engineRating: 275, tonnage: 15.5, integralHeatSinks: 0, maxIntegralHeatSinks: 11 },
  { engineRating: 280, tonnage: 16, integralHeatSinks: 0, maxIntegralHeatSinks: 11 },
  { engineRating: 285, tonnage: 16.5, integralHeatSinks: 0, maxIntegralHeatSinks: 11 },
  { engineRating: 290, tonnage: 17.5, integralHeatSinks: 0, maxIntegralHeatSinks: 11 },
  { engineRating: 295, tonnage: 18, integralHeatSinks: 0, maxIntegralHeatSinks: 11 },
  { engineRating: 300, tonnage: 19, integralHeatSinks: 0, maxIntegralHeatSinks: 12 },
  { engineRating: 305, tonnage: 19.5, integralHeatSinks: 0, maxIntegralHeatSinks: 12 },
  { engineRating: 310, tonnage: 20.5, integralHeatSinks: 0, maxIntegralHeatSinks: 12 },
  { engineRating: 315, tonnage: 21.5, integralHeatSinks: 0, maxIntegralHeatSinks: 12 },
  { engineRating: 320, tonnage: 22.5, integralHeatSinks: 0, maxIntegralHeatSinks: 12 },
  { engineRating: 325, tonnage: 23.5, integralHeatSinks: 0, maxIntegralHeatSinks: 13 },
  { engineRating: 330, tonnage: 24.5, integralHeatSinks: 0, maxIntegralHeatSinks: 13 },
  { engineRating: 335, tonnage: 25.5, integralHeatSinks: 0, maxIntegralHeatSinks: 13 },
  { engineRating: 340, tonnage: 27, integralHeatSinks: 0, maxIntegralHeatSinks: 13 },
  { engineRating: 345, tonnage: 28.5, integralHeatSinks: 0, maxIntegralHeatSinks: 13 },
  { engineRating: 350, tonnage: 29.5, integralHeatSinks: 0, maxIntegralHeatSinks: 14 },
  { engineRating: 355, tonnage: 31.5, integralHeatSinks: 0, maxIntegralHeatSinks: 14 },
  { engineRating: 360, tonnage: 33, integralHeatSinks: 0, maxIntegralHeatSinks: 14 },
  { engineRating: 365, tonnage: 34.5, integralHeatSinks: 0, maxIntegralHeatSinks: 14 },
  { engineRating: 370, tonnage: 36.5, integralHeatSinks: 0, maxIntegralHeatSinks: 14 },
  { engineRating: 375, tonnage: 38.5, integralHeatSinks: 0, maxIntegralHeatSinks: 15 },
  { engineRating: 380, tonnage: 41, integralHeatSinks: 0, maxIntegralHeatSinks: 15 },
  { engineRating: 385, tonnage: 43.5, integralHeatSinks: 0, maxIntegralHeatSinks: 15 },
  { engineRating: 390, tonnage: 46, integralHeatSinks: 0, maxIntegralHeatSinks: 15 },
  { engineRating: 395, tonnage: 49, integralHeatSinks: 0, maxIntegralHeatSinks: 15 },
  { engineRating: 400, tonnage: 52.5, integralHeatSinks: 0, maxIntegralHeatSinks: 16 },
];

export const mechEnginesByRating = mechEngines.reduce(
  (acc, engine) => {
    acc[engine.engineRating] = engine;
    return acc;
  },
  {} as Record<number, MechEngine>,
);
